### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [pierrec/xxHash#2]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for xxHash and versioning would help Debian keep up with development.

**Comment by pierrec** [comment]
Hello,

Thank you for using this project!
I have now tagged the latest version at v0.1.1.

Cheers.

**Comment by aviau** [comment]
Thank you for this!

In the future, please keep tagging as you merge new features and fix bugs :)
