### ISSUE TITLE
Inquery: Is it possible to hash large files without keeping the entire file in RAM?

### ISSUE THREAD

**Issue by nhorvath** [pierrec/xxHash#6]
I'm relatively new to go, so I could be missing something obvious, but is it possible to use this hash to hash a large file in parts so that it doesn't take up the file size worth of ram? I'm trying to hash a video file to detect if it's been modified since last run. Thanks for your help!

**Comment by pierrec** [comment]
Hello,

Yes you can hash large files without holding them in memory.
In fact, the xxsum command line utility does exactly that: it produces the hash of the given input files in a"streaming" fashion, without ever loading the whole files.

Have a look at the source in xxhsum/main.go.

HTH
